export { Header } from './Header'
export { Footer } from './Footer'
export { SectionWrapper } from './SectionWrapper'
export { FloatingNav } from './FloatingNav'
export { ThemeControls } from './ThemeControls'
export { PageWrapper } from './PageWrapper'

export type { HeaderProps, NavigationItem } from './Header'
export type { FooterProps, SocialLink } from './Footer'
export type { SectionWrapperProps } from './SectionWrapper'
export type { FloatingNavProps } from './FloatingNav'
export type { ThemeControlsProps, ThemeMode } from './ThemeControls'
export type { PageWrapperProps } from './PageWrapper'